services:

  nginx:
    image: nginx:1.30-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./main_app:/app
    container_name: app_nginx
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: /docker/php/dev.Dockerfile
    container_name: app_php
    ports:
      - "5173:5173"
    volumes:
      - ./main_app:/app
      - ./docker/php/dev.php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: "1000:1000"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: app_postgres
    environment:
      POSTGRES_DB: pdf_summ
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d pdf_summ" ]
      interval: 5s
      timeout: 5s
      retries: 5

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: app_stripe_cli
    command: listen --forward-to http://nginx/webhook/stripe --skip-verify
    env_file:
      - ./main_app/.env
    environment:
#      STRIPE_API_KEY: "${STRIPE_SECRET}"
      STRIPE_DEVICE_NAME: docker_dev
    networks:
      - app_network
    depends_on:
      - nginx
    restart: on-failure

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
